export const bibleBooks = [
    // Antigo Testamento
    { slug: "genesis", name: "Gênesis", testament: "Antigo Testamento", chapters: 50 },
    { slug: "exodo", name: "Êxodo", testament: "Antigo Testamento", chapters: 40 },
    { slug: "levitico", name: "Levítico", testament: "Antigo Testamento", chapters: 27 },
    { slug: "numeros", name: "Números", testament: "Antigo Testamento", chapters: 36 },
    { slug: "deuteronomio", name: "Deuteronômio", testament: "Antigo Testamento", chapters: 34 },
    { slug: "josue", name: "Josué", testament: "Antigo Testamento", chapters: 24 },
    { slug: "juizes", name: "Juízes", testament: "Antigo Testamento", chapters: 21 },
    { slug: "rute", name: "Rute", testament: "Antigo Testamento", chapters: 4 },
    { slug: "1-samuel", name: "1 Samuel", testament: "Antigo Testamento", chapters: 31 },
    { slug: "2-samuel", name: "2 Samuel", testament: "Antigo Testamento", chapters: 24 },
    { slug: "1-reis", name: "1 Reis", testament: "Antigo Testamento", chapters: 22 },
    { slug: "2-reis", name: "2 Reis", testament: "Antigo Testamento", chapters: 25 },
    { slug: "1-cronicas", name: "1 Crônicas", testament: "Antigo Testamento", chapters: 29 },
    { slug: "2-cronicas", name: "2 Crônicas", testament: "Antigo Testamento", chapters: 36 },
    { slug: "esdras", name: "Esdras", testament: "Antigo Testamento", chapters: 10 },
    { slug: "neemias", name: "Neemias", testament: "Antigo Testamento", chapters: 13 },
    { slug: "ester", name: "Ester", testament: "Antigo Testamento", chapters: 10 },
    { slug: "jo", name: "Jó", testament: "Antigo Testamento", chapters: 42 },
    { slug: "salmos", name: "Salmos", testament: "Antigo Testamento", chapters: 150 },
    { slug: "proverbios", name: "Provérbios", testament: "Antigo Testamento", chapters: 31 },
    { slug: "eclesiastes", name: "Eclesiastes", testament: "Antigo Testamento", chapters: 12 },
    { slug: "cantares", name: "Cantares", testament: "Antigo Testamento", chapters: 8 },
    { slug: "isaias", name: "Isaías", testament: "Antigo Testamento", chapters: 66 },
    { slug: "jeremias", name: "Jeremias", testament: "Antigo Testamento", chapters: 52 },
    { slug: "lamentacoes", name: "Lamentações", testament: "Antigo Testamento", chapters: 5 },
    { slug: "ezequiel", name: "Ezequiel", testament: "Antigo Testamento", chapters: 48 },
    { slug: "daniel", name: "Daniel", testament: "Antigo Testamento", chapters: 12 },
    { slug: "oseias", name: "Oséias", testament: "Antigo Testamento", chapters: 14 },
    { slug: "joel", name: "Joel", testament: "Antigo Testamento", chapters: 3 },
    { slug: "amos", name: "Amós", testament: "Antigo Testamento", chapters: 9 },
    { slug: "obadias", name: "Obadias", testament: "Antigo Testamento", chapters: 1 },
    { slug: "jonas", name: "Jonas", testament: "Antigo Testamento", chapters: 4 },
    { slug: "miqueias", name: "Miquéias", testament: "Antigo Testamento", chapters: 7 },
    { slug: "naum", name: "Naum", testament: "Antigo Testamento", chapters: 3 },
    { slug: "habacuque", name: "Habacuque", testament: "Antigo Testamento", chapters: 3 },
    { slug: "sofonias", name: "Sofonias", testament: "Antigo Testamento", chapters: 3 },
    { slug: "ageu", name: "Ageu", testament: "Antigo Testamento", chapters: 2 },
    { slug: "zacarias", name: "Zacarias", testament: "Antigo Testamento", chapters: 14 },
    { slug: "malaquias", name: "Malaquias", testament: "Antigo Testamento", chapters: 4 },

    // Novo Testamento
    { slug: "mateus", name: "Mateus", testament: "Novo Testamento", chapters: 28 },
    { slug: "marcos", name: "Marcos", testament: "Novo Testamento", chapters: 16 },
    { slug: "lucas", name: "Lucas", testament: "Novo Testamento", chapters: 24 },
    { slug: "joao", name: "João", testament: "Novo Testamento", chapters: 21 },
    { slug: "atos", name: "Atos", testament: "Novo Testamento", chapters: 28 },
    { slug: "romanos", name: "Romanos", testament: "Novo Testamento", chapters: 16 },
    { slug: "1-corintios", name: "1 Coríntios", testament: "Novo Testamento", chapters: 16 },
    { slug: "2-corintios", name: "2 Coríntios", testament: "Novo Testamento", chapters: 13 },
    { slug: "galatas", name: "Gálatas", testament: "Novo Testamento", chapters: 6 },
    { slug: "efesios", name: "Efésios", testament: "Novo Testamento", chapters: 6 },
    { slug: "filipenses", name: "Filipenses", testament: "Novo Testamento", chapters: 4 },
    { slug: "colossenses", name: "Colossenses", testament: "Novo Testamento", chapters: 4 },
    { slug: "1-tessalonicenses", name: "1 Tessalonicenses", testament: "Novo Testamento", chapters: 5 },
    { slug: "2-tessalonicenses", name: "2 Tessalonicenses", testament: "Novo Testamento", chapters: 3 },
    { slug: "1-timoteo", name: "1 Timóteo", testament: "Novo Testamento", chapters: 6 },
    { slug: "2-timoteo", name: "2 Timóteo", testament: "Novo Testamento", chapters: 4 },
    { slug: "tito", name: "Tito", testament: "Novo Testamento", chapters: 3 },
    { slug: "filemom", name: "Filemom", testament: "Novo Testamento", chapters: 1 },
    { slug: "hebreus", name: "Hebreus", testament: "Novo Testamento", chapters: 13 },
    { slug: "tiago", name: "Tiago", testament: "Novo Testamento", chapters: 5 },
    { slug: "1-pedro", name: "1 Pedro", testament: "Novo Testamento", chapters: 5 },
    { slug: "2-pedro", name: "2 Pedro", testament: "Novo Testamento", chapters: 3 },
    { slug: "1-joao", name: "1 João", testament: "Novo Testamento", chapters: 5 },
    { slug: "2-joao", name: "2 João", testament: "Novo Testamento", chapters: 1 },
    { slug: "3-joao", name: "3 João", testament: "Novo Testamento", chapters: 1 },
    { slug: "judas", name: "Judas", testament: "Novo Testamento", chapters: 1 },
    { slug: "apocalipse", name: "Apocalipse", testament: "Novo Testamento", chapters: 22 },
];